"""Add ProductChunk table

Revision ID: 203414a4742d
Revises: 95896e554811
Create Date: 2026-05-26 12:48:20.476989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '203414a4742d'
down_revision: Union[str, Sequence[str], None] = '95896e554811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_chunks_id'), 'product_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_product_chunks_product_id'), 'product_chunks', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_chunks_product_id'), table_name='product_chunks')
    op.drop_index(op.f('ix_product_chunks_id'), table_name='product_chunks')
    op.drop_table('product_chunks')
    # ### end Alembic commands ###
