"""Add mrp to Product

Revision ID: 6160e0339db4
Revises: 203414a4742d
Create Date: 2026-05-28 13:06:40.860188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6160e0339db4'
down_revision: Union[str, Sequence[str], None] = '203414a4742d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('mrp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'mrp')
    # ### end Alembic commands ###
